---
- name: Detecting existing PyPI installation
  ansible.builtin.stat:
    path: "{{ ara_api_venv_path }}"
  register: existing_pypi_install

- name: Notify about existing PyPI installation
  ansible.builtin.debug:
    msg: |
      You seem to have ARA-API installed via PyPI in the past, you might
      want to clean up that installation and migrate your data
  when: existing_pypi_install['stat']['exists']

- name: Override file locations with path in container
  ansible.builtin.set_fact:
    ara_api_database_name: "/opt/ara/ansible.sqlite"
    ara_api_log_dir: "/opt/ara/logs"
    ara_api_settings: "{{ ara_api_root_dir }}/settings.yaml"

- name: Set up volume mount path
  ansible.builtin.set_fact:
    # could also be ternaries ¯\_(ツ)_/¯
    _volume_mount: >-
      {% if ansible_facts['selinux']['status'] == 'enabled' %}
      {{ ara_api_root_dir}}:/opt/ara:z
      {% else %}
      {{ ara_api_root_dir}}:/opt/ara
      {% endif %}

    _systemd_dir: >-
      {% if ansible_user_id == 'root' %}
      /etc/systemd/service
      {% else %}
      {{ ansible_user_dir }}/.config/systemd/user
      {% endif %}

- name: Pull and run an ara-api container
  containers.podman.podman_container:
    name: ara-api
    image: "{{ ara_api_image }}:{{ ara_api_version }}"
    pull: newer
    state: present
    auto_remove: true
    ports:
      - 127.0.0.1:8000:8000
    volume:
      # TODO: troubleshoot option :z breaking when selinux is enabled
      - "{{ _volume_mount }}"

- name: Create a systemd directory if we're unprivileged
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user"
    mode: "0755"
    recurse: true
    state: present
  # maybe we could check the uid of effective_uid instead
  when: "ansible_user_id != 'root'"

- name: Set up systemd unit file for the podman container
  containers.podman.podman_generate_systemd:
    name: ara-api
    container_prefix: ""
    separator: ""
    # ^ maybe these above should be configurable
    dest: "{{ _systemd_dir }}"
    restart_policy: always
    use_names: true
    new: true

- name: Enable and start the systemd service
  ansible.builtin.systemd:
    name: ara-api
    scope: "{{ ansible_user_id == 'root' | ternary(omit, 'user') }}"
    daemon_reload: true
    state: started
    enabled: true
